config/routes.rb
Rails.application.routes.draw do
  get 'agent_websites/import'
  get 'profile/show'
  get 'agent_websites/crawler'
  get 'agent_websites/settings'
  get 'agent_websites/trendings'



  root to: 'welcom#index'

  resources :dummies
  devise_for :agents
  resources :agent_websites
end

app/models/dummy.rb
# == Schema Information
#
# Table name: dummies
#
#  id         :integer          not null, primary key
#  fis_id     :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Dummy < ApplicationRecord
end

app/controllers/dummies_controller.rb
class DummiesController < ApplicationController

  def index
    session_key=0
    header_set = request.headers['api-key']
		session_key = request.headers['session-key']
    prod = request.headers['product']
    
    if website = AgentWebsite.find_by(website_api_key: header_set)
     # if (!session_key.nil? && profile = Profiler.find_by(session_key: session_key))
      #    Profiler.expiry_check(profile , params[:product_name] , website) 

      ####agent info Section###
      @agent_info=Agent.find_by(id: website.agent_id)
      @agent_web=website

      if session_key.nil? 
      ##@agent_session=9898
      #new session creations
      # Profiler.without_session
       #Bilawaja.upgrade
      @agent_session=Mango.without_session(params[:product_name])

      else 
      @agent_session=session_key
      ##expiry checker

      ## expiry_check
      Mango.session(params[:product_name] ,@agent_session)

      end
      

      #####end ##########
        if params[:product_name]
          @sets = FrequentItemSet.where('item like ?' , "%#{params[:product_name]}%")
          if !@sets.empty?
            array_name = @sets[0].item.split(',')
            array_name = array_name.map {|a| a.gsub(/({|}|")/,'')}
            @arr = []
            array_name.each do |a|
            @arr << Product.find_by(name: a)
            end 
          end 
    #   else
    #     Profiler.without_session(website , params[:product_name]) 
    #   end
      # render json: @arr
          @arr= @arr.to_json
        end    
      else

      @api_error = JSON.parse('{"ERROR": "API-Key invalid"}')
      render  'show'    
    end
  end

 # if request.env["HTTP_REFERER"].present? and request.env["HTTP_REFERER"] != request.env["REQUEST_URI"]
 #      redirect_to :back
 #    else
 #       render nothing: true
 #    end
 end

app/helpers/dummies_helper.rb
module DummiesHelper
end

app/views/dummies/_form.html.erb
<%= form_for(dummy) do |f| %>
  <% if dummy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dummy.errors.count, "error") %> prohibited this dummy from being saved:</h2>

      <ul>
      <% dummy.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fis_id %>
    <%= f.number_field :fis_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dummies/edit.html.erb
<h1>Editing Dummy</h1>

<%= render 'form', dummy: @dummy %>

<%= link_to 'Show', @dummy %> |
<%= link_to 'Back', dummies_path %>

app/views/dummies/index.html.erb
<p id="notice"><%= notice %></p>

  


 <h1>Session #  <%= @agent_session %></h1> 
  <h1>Agent: <%= @agent_info.first_name %></h1><br>
<h2>Agent website link : <%= @agent_web.website_link %></h2>	<br>
<br><br><br>
<h2>Selected frequent Item set: </h2>
<%= @sets.first.item if @sets%>
<br><br><br>
<h2>Availble Products for Recommendation Restults: </h2><%= @arr %>

app/views/dummies/new.html.erb
<h1>New Dummy</h1>

<%= render 'form', dummy: @dummy %>

<%= link_to 'Back', dummies_path %>

app/views/dummies/show.html.erb
  <%= @api_error["ERROR"] %>
 