config/routes.rb
Rails.application.routes.draw do
  get 'agent_websites/import'
  get 'profile/show'
  get 'agent_websites/crawler'
  get 'agent_websites/settings'
  get 'agent_websites/trendings'



  root to: 'welcom#index'

  resources :dummies
  devise_for :agents
  resources :agent_websites
end

app/models/agent_website.rb
# == Schema Information
#
# Table name: agent_websites
#
#  id              :integer          not null, primary key
#  website_link    :string(255)
#  website_api_key :string(255)
#  agent_id        :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class AgentWebsite < ApplicationRecord
  belongs_to :agent
  before_save do
		create_website_api_key(self)   	
  end

  def create_website_api_key(website)
	str =  Base64.encode64((0...20).map { ('a'..'z').to_a[rand(26)] }.join)	
	str = str[0..str.length-2]
	website.website_api_key = str  
	end

  def self.create_website_api_key2(website)
		str =  Base64.encode64((0...20).map { ('a'..'z').to_a[rand(26)] }.join)     
    str = str[0..str.length-2]
    website.website_api_key = str
  	website.save!
  end

end

app/controllers/agent_websites_controller.rb
class AgentWebsitesController < ApplicationController
  before_action :authenticate_agent!
  before_action :set_agent_website, only: [:show, :edit, :update, :destroy]
  layout "dum"


  # GET /agent_websites
  # GET /agent_websites.json
  def index
    @agent_websites = current_agent.agent_websites
  end

  # GET /agent_websites/1
  # GET /agent_websites/1.json
  def show
    AgentWebsite.create_website_api_key2(@agent_website)
    redirect_to agent_websites_path
  end

  # GET /agent_websites/new
  def new
    @agent_website = AgentWebsite.new
  end

  # GET /agent_websites/1/edit
  def edit
  end

  # POST /agent_websites
  # POST /agent_websites.json
  def create
    @agent_website = AgentWebsite.new(agent_website_params)
    @agent_website.agent_id = current_agent.id
    respond_to do |format|
      if @agent_website.save
        format.html { redirect_to @agent_website, notice: 'Agent website was successfully created.' }
        format.json { render :show, status: :created, location: @agent_website }
      else
        format.html { render :new }
        format.json { render json: @agent_website.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /agent_websites/1
  # PATCH/PUT /agent_websites/1.json
  def update
    respond_to do |format|
      if @agent_website.update(agent_website_params)
        format.html { redirect_to @agent_website, notice: 'Agent website was successfully updated.' }
        format.json { render :show, status: :ok, location: @agent_website }
      else
        format.html { render :edit }
        format.json { render json: @agent_website.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /agent_websites/1
  # DELETE /agent_websites/1.json
  def destroy
    @agent_website.destroy
    respond_to do |format|
      format.html { redirect_to agent_websites_url, notice: 'Agent website was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

def crawler

end

def settings
  
end

def import
  
end

def trendings
  
end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_agent_website
      @agent_website = AgentWebsite.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def agent_website_params
      params.require(:agent_website).permit(:website_link, :website_api_key)
    end
end

app/helpers/agent_websites_helper.rb
module AgentWebsitesHelper
end

app/views/agent_websites/_form.html.erb
<%= form_for(agent_website) do |f| %>
  <% if agent_website.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(agent_website.errors.count, "error") %> prohibited this agent_website from being saved:</h2>

      <ul>
      <% agent_website.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="row">
    <div class="col-sm-4">

<form>

  <div class="field">
    <%= f.label :website_link %>
    <%= f.text_field :website_link, class:"form-control" ,placeholder:"http://yoursite.com"%>
  </div>

<div class="form-group">
     <small id="passwordHelpInline" class="text-muted">
      Must be 8-20 characters long.
    </small>
  </div>

  <div class="actions">
    <%= f.submit class:"btn btn-primary"%>
  </div>



<!--   <div class="form-group">
    <label for="formGroupExampleInput">Example label</label>
    <input type="text" class="form-control" id="formGroupExampleInput" placeholder="Example input">
  </div>
 -->  

    <!-- <div class="form-group">
    <label for="formGroupExampleInput2">Another label</label>
    <input type="text" class="form-control" id="formGroupExampleInput2" placeholder="Another input">
     <small id="passwordHelpInline" class="text-muted">
      Must be 8-20 characters long.
    </small>
  </div>
   <button type="submit" class="btn btn-primary">Submit</button>

    -->
</form>  
  </div>
</div>
<% end %>

app/views/agent_websites/crawler.html.erb
    <div class="container">
        <div class="row">
            <div class="col-sm-6">
              <h2>Add Crawler</h2>
              <p>Turn on the sites which you want to get crawl</p>            
              <table class="table">
                <thead>
                  <tr>
                    <th>Sites</th>

                    <th> </th>
                </tr>
                </thead>
                <tbody>
                <tr>
                <td><h4>www.daraz.pk</h4></td>
                <td>
                    <div class="col-sm-6 pull-right">                   
                       <div class="onoffswitch">
                            <input type="checkbox" name="onoffswitch" class="onoffswitch-checkbox" id="myonoffswitch" checked>
                            <label class="onoffswitch-label" for="myonoffswitch">
                                <span class="onoffswitch-inner"></span>
                                <span class="onoffswitch-switch"></span>
                            </label>
                        </div>
                    </div>
                </td>
            </tr>
            <tr>
                <td><h4>www.kaymu.pk</h4></td>

                <td>
                    <div class="col-sm-6 pull-right">        
                        <div class="onoffswitch">
                            <input type="checkbox" name="onoffswitch" class="onoffswitch-checkbox" id="myonoffswitch" checked>
                            <label class="onoffswitch-label" for="myonoffswitch">
                                <span class="onoffswitch-inner"></span>
                                <span class="onoffswitch-switch"></span>
                            </label>
                        </div>
                    </div>

                </td>
            </tr>
            <tr>
                <td><h4>www.mega.pk</h4></td>
                <td>
                    <div class="col-sm-6 pull-right">        
                        <div class="onoffswitch ">
                            <input type="checkbox" name="onoffswitch" class="onoffswitch-checkbox" id="myonoffswitch" checked>
                            <label class="onoffswitch-label" for="myonoffswitch">
                                <span class="onoffswitch-inner"></span>
                                <span class="onoffswitch-switch"></span>
                            </label>
                        </div>
                    </div>
                </td>
            </tr>
    </tbody>
</table>
</div>
</div>


<input id="ex6" type="text" data-slider-min="-5" data-slider-max="20" data-slider-step="1" data-slider-value="3"/>
<span id="ex6CurrentSliderValLabel">Current Slider Value: <span id="ex6SliderVal">3</span></span>

</div>

app/views/agent_websites/edit.html.erb
<h1>Editing Agent Website</h1>

<%= render 'form', agent_website: @agent_website %>

<%= link_to 'Show', @agent_website %> |
<%= link_to 'Back', agent_websites_path %>

app/views/agent_websites/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Agent Websites</h1>


<%= link_to 'New Agent Website', new_agent_website_path, class:"btn btn-warning glyphicon glyphicon-new-window"  %>

<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>Website link</th>
      <th>Website api key</th>
      <th>Agent</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @agent_websites.each do |agent_website| %>
      <tr>
        <td><%= agent_website.website_link %></td>
        <td><%= agent_website.website_api_key %></td>
        <td><%= agent_website.agent.first_name %></td>

        <td><%= link_to ' Regenerate', agent_website , class:"btn btn-success glyphicon glyphicon-refresh"%></td>
        <td><%= link_to ' Edit', edit_agent_website_path(agent_website), class:"btn btn-warning glyphicon glyphicon-new-window" %></td>
        <td><%= link_to ' Destroy', agent_website,class:"btn btn-danger glyphicon glyphicon-remove", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= @agent %>

app/views/agent_websites/new.html.erb
<h1>New Agent Website</h1>

<%= render 'form', agent_website: @agent_website %>

<%= link_to 'Back', agent_websites_path %>

app/views/agent_websites/settings.html.erb
<h1>Choose Your Recommendations Limit</h1>
<div class="dgradio-sb ">
  <input type="radio" class="dg-item" name="your-group-2" id="radio6" />
  <label for="radio6" class="dg-label dg-10"  data-caption="1-3">
    Minimum<span class="dg-bg"></span>
  </label>

  <input type="radio" class="dg-item" name="your-group-2" id="radio7" checked="checked"/>
  <label for="radio7" class="dg-label dg-30"  data-caption="5-10">
    Average<span class="dg-bg"></span>
  </label>

  <input type="radio" class="dg-item" name="your-group-2" id="radio8" >
  <label for="radio8" class="dg-label dg-50"  data-caption="10-15">
    Vaerity <span class="dg-bg"></span>
  </label>

  <input type="radio" class="dg-item" name="your-group-2" id="radio9" />
  <label for="radio9" class="dg-label dg-100"  data-caption="all availble!">
    Maximun<span class="dg-bg"></span>
  </label>

</div>