config/routes.rb
Rails.application.routes.draw do
  get 'agent_websites/import'
  get 'profile/show'
  get 'agent_websites/crawler'
  get 'agent_websites/settings'
  get 'agent_websites/trendings'



  root to: 'welcom#index'

  resources :dummies
  devise_for :agents
  resources :agent_websites
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
    <title>Abr</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%if signed_in?%>
    	<%= link_to 'Logout' , destroy_agent_session_path , method: :delete %>
  <% end %>

    <%= yield %>
    
  </body>
</html>

app/views/layouts/dum.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>mango</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'dum', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%if signed_in? %>
  <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.html">Admin Panel</a>

            </div>
            <!-- Top Menu Items -->
            <ul class="nav navbar-right top-nav">
                
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i><%=current_agent.first_name%><b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li>
                            <!-- <a href="#"><i class="fa fa-fw fa-user"></i> Profile</a> -->

                         <%= link_to " Edit Profile", edit_agent_registration_path, class: "fa fa fa-user" %> 

                        </li>
                      
                        <li class="divider"></li>
                        <li>
                           <%= link_to 'Log Out' , destroy_agent_session_path , method: :delete %>
                        </li>
                    </ul>
                </li>
            </ul>
            <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav side-nav">
                    <li class="active">
                        <a href="index.html"><i class="fa fa-fw fa-dashboard"></i> Dashboard</a>
                    </li>
                   
                     <li>    
                       <!--  <a href="forms.html"><i class="fa fa-fw fa-edit"></i> Add Website</a> -->

                        <%= link_to '  Add Website', new_agent_website_path, class:"fa fa fa-edit"  %>

                    </li>
                    
                    <li>
                        <!-- <a href="tables.html"><i class="fa fa-fw fa-table"></i> Products</a> -->

                         <%= link_to "  Products", profile_show_path, class: "fa fa fa-table" %> 

                    </li>
                   <li>
                        <a href="javascript:;" data-toggle="collapse" data-target="#demo"><i class="fa fa-fw fa-wrench"></i> Prefrences<i class="fa fa-fw fa-caret-down"></i></a>
                        <ul id="demo" class="collapse">
                            <li>
                                 <!-- <a href="charts.html"><i class="fa fa-fw fa-bar-chart-o"></i> Crawlers</a>
 -->
                                 <%= link_to '  Crawlers', agent_websites_crawler_path, class:"fa fa fa-bar-chart-o"  %>
                            </li>

                            <li>
                                 <!-- <a href="charts.html"><i class="fa fa-fw fa-arrows-v"></i> Set Recommendations</a> -->
                                 <%= link_to ' Set Recommendations', agent_websites_settings_path, class:"fa fa fa-arrows-v"  %>

                            </li>
                        </ul>
                    </li>
                    <li>
                        <!-- <a href="bootstrap-elements.html"><i class="fa fa-fw fa-desktop"></i> Import Products</a> -->
                        <%= link_to " Import Products", agent_websites_import_path, class: "fa fa-desktop" %> 
                    </li>
                    <li>
                        <!-- <a href="bootstrap-grid.html"><i class="fa fa-fw fa-fire"></i> Trends</a> -->
                                 <%= link_to ' Trendings', agent_websites_trendings_path, class:"fa fa fa-fire"  %>
                   
                    

                    </li>
                    
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </nav>

        <div id="page-wrapper">

            <div class="container-fluid">

                <!-- Page Heading -->
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">
                            Dashboard <small>Statistics Overview</small>

                          
                        </h1>
                        <ol class="breadcrumb">
                            <li class="active">
                                <i class="fa fa-dashboard"></i> Dashboard
                            </li>
                        </ol>
                    </div>
                </div>
                <!-- /.row -->

                
                    <!-- /.row -->

                <div class="anglo">
                            <%=yield%>
                </div>
            </div>
            <!-- /.container-fluid -->
                    

        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

</body>
  <% end %>
  </body>
</html>

app/views/layouts/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>welcome</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'index', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%if signed_in? %>
      <%= link_to 'Logout' , destroy_agent_session_path , method: :delete %>
  <% end %>

    <%= yield %>
    
  </body>
</html>

app/views/layouts/table.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>welcome</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'table', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
  <div class="container-fluid">
    <%= yield %>


</div>

    
  </body>
</html>